language: "node_js"

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

env:
  global:
    - export NODE_ENV=test

script:
  - yarn test

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
